### ISSUE TITLE
Will this tool allow rebinding specific souls/glyphs to special moves?

### ISSUE THREAD

**Issue by DarkWave0** [LagoLunatic/DSVEdit#1]
A bit of ridiculous request I imagine. I really do not enjoy the menu switching of the DS cv games. Having a wider aray of skills/transformations/specials to use in real time without menu switching seems like a nice idea. Would it be possible with this tool to make triggers for that or do I need some ASM-type coding skills? 

If not, is it possible to add something like that as a feature?
Look at what's possible in sotn because of the control system: https://sites.google.com/site/darkwavestyle/games-research/castlevania-symphony-of-the-night-ps1-psp-360

**Comment by LagoLunatic** [comment]
I'm pretty sure anything changing the control system will require ASM code. Something as simple as changing the default button configuration may or may not need it, but if you want to hardcode a certain button to a certain glyph, or make a button combo like "up left down right A" trigger a special move, you'll definitely need ASM.

Specifically what you'd need to do is modify the update code of the player character in question to check for the button/button combo you want, check if the player actually owns the item in question, and then call some function to use the skill you want it to.

**Comment by DarkWave0** [comment]
Thank you for explaining. That is most likely beyond my level of expertise. I'll have a look at some ASM info and see if it's learnable. Have fun with the tool, it looks excellent.

**Comment by LagoLunatic** [comment]
Let me know if you need the location of something in ram, like byte 02100421 controlling whether the player owns magnes yet for example. I know where a lot of that kind of stuff is already.
