### ISSUE TITLE
Add/remove/edit health costs for glyphs in OoE

### ISSUE THREAD

**Issue by appleforyou** [LagoLunatic/DSVEdit#10]
I have some ideas in mind that would benefit from being able to add or edit health costs on glyphs. As far as I've seen this isn't an option in dsvedit -- have you identified where the health cost is calculated?

**Comment by LagoLunatic** [comment]
It's hardcoded into the functions for using the dominus glyphs. If you want to change the percent/amount of HP they reduce you'll need to modify their ASM code. If you want to add a health cost to a non-dominus glyph you'll need to write brand new code to reduce health and insert it into the function for whatever glyph you want. Doing this via DSVEdit's UI is not possible.
