### ISSUE TITLE
Aria of Sorrow Soma Status for DSVania Tool

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#12]
hello, I have SOMA status offsets for you to add to DSVania Tool
you can see in the picture

https://i.imgur.com/DIG3taf.png

please talk to me "folgore2013@hotmail.com"

**Comment by LagoLunatic** [comment]
Uh, you mean where Soma's stats are located in RAM? I already have that in the docs: https://github.com/LagoLunatic/DSVEdit/blob/master/docs/AoS%20RAM%20Map.txt
Also your screenshot doesn't even include the addresses so it's pointless.
I'm not going to email you.

**Comment by Urahara666** [comment]
> Uh, you mean where Soma's stats are located in RAM? I already have that in the docs: https://github.com/LagoLunatic/DSVEdit/blob/master/docs/AoS%20RAM%20Map.txt
> Also your screenshot doesn't even include the addresses so it's pointless.
> I'm not going to email you.

no need to talk like that friend
I would pass the addresses if you didn't have '-'
Do you know how to change Soma's walking speed and jump height?

**Comment by LagoLunatic** [comment]
Nope. The values are probably hardcoded somewhere in the `PlayerSomaUpdate` function.

**Comment by Urahara666** [comment]
ok do you intend to add circle of the moon to the tool?

**Comment by LagoLunatic** [comment]
CotM has a completely separate engine and was coded by a different team so that's not possible.
I also don't intend to create a new editor from scratch just for CotM.

**Comment by Urahara666** [comment]
the maximum value of HP is 1496
How do I exceed this value?

**Comment by LagoLunatic** [comment]
I have no idea what that means. You need to explain yourself better if you want people to understand you.

Also, this is a bug tracker for DSVEdit, not a place to ask questions unrelated to DSVEdit's functionality. Whatever the phrase "exceeding the maximum value of HP" might mean it's not a feature DSVEdit has so you will need to figure out how to hack the game to do this thing yourself. I'm locking this thread.
