### ISSUE TITLE
Icon Edit

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#13]
it's not a problem but a question
Can you add a function to edit item icons?

**Comment by LagoLunatic** [comment]
Already exists. Select the item, click the button next to icon, and it will open a dialog to let you choose which icon to use.

If you want to edit the actual image data of the icons sheet to have custom graphics, copy paste both the file path and the palette ptr out of the icon chooser dialog into the GFX editor, and then you can edit the GFX and palettes there like with any other image.

**Comment by Urahara666** [comment]
I wanted to like take the icon of some item from Dawn of Sorrow and put it in aria's place.

**Comment by LagoLunatic** [comment]
Yes that should be quite easy.

**Comment by Urahara666** [comment]
do you have any tutorials for me to learn?

**Comment by LagoLunatic** [comment]
You might wanna read the file called "README".
Specifically, this section. https://github.com/LagoLunatic/DSVEdit#how-to-edit-gfx-and-palettes

**Comment by Urahara666** [comment]
unfortunately I can't '-'
all palettes change

**Comment by piratesephiroth** [comment]
and if you read there you know that you can also modify the palette
