### ISSUE TITLE
Weakness

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#14]
can you tell me what the resistance and weakness 13, 14 etc ... mean
and these unknow on weapons and equipment.

https://i.imgur.com/Tu2CDwh.png
https://i.imgur.com/gLCHXDJ.png

**Comment by LagoLunatic** [comment]
They either don't do anything, or they do something I don't know about, which is why I haven't given them useful names. If they actually do something and you figure out exactly what that is tell me and I'll give them better names.
