### ISSUE TITLE
Rycuda Soul

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#18]
hello, I wanted to try to exchange Rycuda DoS soul sprite for AoS Lightining Doll, but I don't find Rycuda's sprite in the editor '-'

**Comment by LagoLunatic** [comment]
It's in the common sprite, frames D6 D7 and D8

Because it's in the common sprite, I assume other things in the game besides that soul use it, so when you change that expect other lightning in the game to look different too
