### ISSUE TITLE
identified var

### ISSUE THREAD

**Issue by DragonZealot** [LagoLunatic/DSVEdit#2]
in the item editor > weapons, unknown 4 is actually the iframes between hits. im not sure the exact number.
examples:
set it to 0, and it will do continuous damage as long as the hitbox is active,
set it to FFFF and it will only hit an enemy once. (timer for iframes is too long)

**Comment by LagoLunatic** [comment]
Ooh nice, I wasn't expecting that to be in the item data. Thanks!
It looks like the thing I was calling unknown 4 is actually two different numbers, the low byte is the iframes and the high byte is the sprite animation for throwing weapons.
I also managed to find iframes for weapons in PoR and glyphs in OoE.

**Comment by DragonZealot** [comment]
cool. i dont have a romhacking.net account and there are no pms in github.
i would love to collaborate to help you with the editor.

**Comment by LagoLunatic** [comment]
Any help would be much appreciated :)

If you wanted to contact me outside github you could friend me on discord (LagoLunatic#6865)
