### ISSUE TITLE
[DoS] early doppelganger issues

### ISSUE THREAD

**Issue by barp0** [LagoLunatic/DSVEdit#21]
when i put a doppelganger candle in the second room of the lost village, getting the soul worked, but it also caused me to be able to double jump. when i checked the abilities menu, i saw it didn't even give me malphas, just its effect. i replaced it with a hippogryph candle, and it gave the hippogryph soul and the doppelganger effects. any ideas of what could be causing this or if it's preventable? it should be noted that this was not the only modification i made, (i can give a list if necessary) but nothing else i did seems like it'd affect this

**Comment by barp0** [comment]
also: hippogryph did not give me the malphas effects. i also tried making doppelganger a free soul, but the same thing happened

**Comment by LagoLunatic** [comment]
This is a bug present in vanilla DoS. You can actually trigger it in vanilla if you sequence break the game and get a different ability soul besides Balore as your first.

I wrote an ARMIPS patch that fixes this bug a long time ago, so I highly recommend applying the patch to your project so this issue doesn't occur: https://github.com/LagoLunatic/DSVEdit/blob/master/asm/dos_fix_first_ability_soul.asm
(If you're curious about the janky programming that causes the bug to happen in the first place, you can read the explanation of it I wrote inside the patch itself.)

**Comment by barp0** [comment]
thank you
