### ISSUE TITLE
[DoS] help negating soul upgrade system?

### ISSUE THREAD

**Issue by barp0** [LagoLunatic/DSVEdit#22]
is there a way to make souls act like how they do at 9 no matter how many you have? if not, could you make an armips that does this? maybe an armips that makes soul release give you souls if that's easier? (i always thought the DoS upgrade system was annoying)

**Comment by LagoLunatic** [comment]
I'm not interested in writing a patch for that.
If you plan to write one you can take a look at my documentation: https://github.com/LagoLunatic/DSVEdit/tree/master/docs
