### ISSUE TITLE
GBA dummy file readsystem error for AOS

### ISSUE THREAD

**Issue by watermelonsplash666** [LagoLunatic/DSVEdit#24]
Hi Lagolunatic,
First of all, thank you for your contribution to this fabulous multipurpose editor for Castlevania games. I have been using this tool and experienced no issues as it works like a charm to me. However, after I edited the map of Castlevania Aria of sorrow yesterday, I was unable to open the edited file on the next day for my next edit. It kept displaying the following message in the screenshot. Thanks for your help.
![image (13)](https://user-images.githubusercontent.com/62620477/77469207-f71ec900-6dcb-11ea-938a-4144f1b2e4d1.png)

**Comment by LagoLunatic** [comment]
I'll need to know the exact actions you took that lead to this occurring. Seems like a layer for one of the rooms in the game got corrupted.

I recommend reverting to a backup of your hack from before the crash was happening, and try retracing your steps to do the same things you did yesterday. Then save it, and open it. Once you've figured out what causes the corruption, tell me the exact steps and I'll see if I can reproduce it on a clean AoS project.

**Comment by LagoLunatic** [comment]
Closing this since no response, but feel free to open a new issue if you figure out the steps to reproduce it.
