### ISSUE TITLE
error to open

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#25]
hey man, a friend has this error from version 1.9.0 64 bits
canb you help ?

https://i.imgur.com/8i6LLA4.png

**Comment by LagoLunatic** [comment]
From the readme:

> Requirements
> 
> The path where DSVEdit is located must only have ASCII characters in it - the program will not launch if there are any unicode characters in it.
> 
> Install Visual C++ Redistributable for Visual Studio 2015: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Your username has unicode characters in it. Move DSVEdit to some other folder that is not in your user folder.

**Comment by Urahara666** [comment]
the program is in the downloads folder and already has the program installed and gives the same error
