### ISSUE TITLE
Free Space I Guess

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#30]
what to do when this message appears?

https://i.imgur.com/ZjslKzT.png

**Comment by LagoLunatic** [comment]
It's not related to free space. Just ignore it.

**Comment by Urahara666** [comment]
I tried to add an item in The Lost Village and it didn't work '-' a candle with a soul
can you tell me if something is wrong?

https://i.imgur.com/CDaS29t.png
https://i.imgur.com/kwXdq4Y.png

**Comment by LagoLunatic** [comment]
Nothing is wrong. If it doesn't show up in game, that just means you already own the Cave Troll soul in your test save file. Soul candles don't appear if you already own them.
