### ISSUE TITLE
Sprite

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#36]
when I try to change the color of these sprites it shows this error and when I save the file, the editing does not work
i'm using last version Dsvania

https://uploaddeimagens.com.br/imagens/KcQPIOI

**Comment by LagoLunatic** [comment]
Editing Loretta's palette in the GFX editor works normally and displays results ingame for me.

The warnings in your screenshot aren't a bug, they just show up when there are parts that are 0x0 in size, which Loretta has in vanilla for whatever reason.

**Comment by Urahara666** [comment]
editing doesn't work here, what do I do?
