### ISSUE TITLE
Editing the hitbox for Peeping Eye (Castlevania AOS)

### ISSUE THREAD

**Issue by watermelonsplash666** [LagoLunatic/DSVEdit#37]
Hey Lago~
I hope this thread finds you well. Please note that this is not an issue or bug related to the editor itself. Dsv has been working like a charm for me as always. It is just a question for my personal project. 

I edited a lot of sprites and animations using the darkfunction feature of the program for my personal project. Upon recently, I decided to lay my hands on the peeping eye enemy, which is to be replaced with the Peeping Big from Harmony of Dissonance. When I exported the animation to darkfunction editor, the hitbox of the enemy is not shown like the other enemies I edited before. I wonder if the hitbox is hardcoded? If so, is there a way to make the hitbox bigger by any chance? 

Thank you so much for your help my friend:D

**Comment by LagoLunatic** [comment]
Sorry, no clue how its hitboxes work. It's not in the sprite data, so not a bug.
I assume it must be hardcoded, but I can't find anything in peeping eye's code that works with anything I have documented related to hitboxes.
