### ISSUE TITLE
Portrait of Ruin

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#39]
do you know how to change the initial status of Richter mode?
like ATK, DEF, HP, Etc..

i know how to do this in aria of sorrow and would be nice if you add this function in dsvania

**Comment by LagoLunatic** [comment]
It's already in the docs, "List of starting/base stats for each player."

**Comment by Urahara666** [comment]
I can't find it, would it be here?
https://i.imgur.com/H7czVFG.png

**Comment by LagoLunatic** [comment]
PoR RAM Map.txt

**Comment by Urahara666** [comment]
I'm trying to change the values ​​by hexadecimal, but I can't find the offsets '-' are they in that file?

**Comment by Urahara666** [comment]
I'm trying to change the values ​​by hexadecimal, but I can't find the offsets '-' are they in that file?

**Comment by Urahara666** [comment]
Can you help me please ?

**Comment by LagoLunatic** [comment]
I've already spoonfed you the answer. I told you exactly where the info you need is, there's nothing more I can tell you. Repeatedly posting comments and deleting them isn't going to accomplish anything, stop making a nuisance of yourself please.
