### ISSUE TITLE
DSVEdit crashes on extracting/opening Portrait of Ruin JPN version

### ISSUE THREAD

**Issue by kseptuple** [LagoLunatic/DSVEdit#4]
DSVEdit crashes on extracting/opening Portrait of Ruin JPN version. Both x64 and x86 version crashes.
It seems to have extracted the ROM successfully but crashes while loading files.

Log:

---first try, extract the rom---
E, [2017-08-09T14:52:45.967756 #1492] ERROR -- : undefined method `[]=' for nil:NilClass (NoMethodError)
E:/test/build/DSVania Editor/dsvlib/nds_file_system.rb:758:in `get_assets'
E:/test/build/DSVania Editor/dsvlib/nds_file_system.rb:44:in `open_and_extract_rom'
E:/test/build/DSVania Editor/dsvlib/game.rb:55:in `initialize_from_rom'
E:/test/build/DSVania Editor/dsvedit/main_window.rb:284:in `extract_rom'
E:/test/build/DSVania Editor/dsvedit/main_window.rb:262:in `extract_rom_dialog'
E:/test/build/DSVania Editor/lib/ruby/gems/2.2.0/gems/qtbindings-4.8.6.2-x86-mingw32/lib/Qt/qtruby4.rb:479:in `qt_metacall'
E:/test/build/DSVania Editor/lib/ruby/gems/2.2.0/gems/qtbindings-4.8.6.2-x86-mingw32/lib/Qt/qtruby4.rb:479:in `method_missing'
E:/test/build/DSVania Editor/lib/ruby/gems/2.2.0/gems/qtbindings-4.8.6.2-x86-mingw32/lib/Qt/qtruby4.rb:479:in `exec'
E:/test/build/DSVania Editor/./dsvedit.rb:26:in `<main>'

---second try, open the folder which seems to be extracted successfully---
E, [2017-08-09T14:56:50.050162 #1972] ERROR -- : undefined method `[]=' for nil:NilClass (NoMethodError)
E:/test/build/DSVania Editor/dsvlib/nds_file_system.rb:758:in `get_assets'
E:/test/build/DSVania Editor/dsvlib/nds_file_system.rb:35:in `open_directory'
E:/test/build/DSVania Editor/dsvlib/game.rb:32:in `initialize_from_folder'
E:/test/build/DSVania Editor/dsvedit/main_window.rb:307:in `open_folder'
E:/test/build/DSVania Editor/dsvedit/main_window.rb:271:in `open_folder_dialog'
E:/test/build/DSVania Editor/lib/ruby/gems/2.2.0/gems/qtbindings-4.8.6.2-x86-mingw32/lib/Qt/qtruby4.rb:479:in `qt_metacall'
E:/test/build/DSVania Editor/lib/ruby/gems/2.2.0/gems/qtbindings-4.8.6.2-x86-mingw32/lib/Qt/qtruby4.rb:479:in `method_missing'
E:/test/build/DSVania Editor/lib/ruby/gems/2.2.0/gems/qtbindings-4.8.6.2-x86-mingw32/lib/Qt/qtruby4.rb:479:in `exec'
E:/test/build/DSVania Editor/./dsvedit.rb:26:in `<main>'

**Comment by LagoLunatic** [comment]
For the JP version of PoR, there are two versions. The original release (release number 0676) and revision 01 (release number 6079). DSVEdit only supports revision 01. That crash with that error is what you get when you try to open the original release.

I'm not adding support for the original version since it's a lot of work to support each version and I don't know of any benefit to the original version over revision 01. Maybe I should try to detect that version and give an error message though instead of crashing.

**Comment by kseptuple** [comment]
Thank you. I've actually tested on a rom that claimed to be rev 01 but in fact the original one. Now I've got the correct rom and it works.
