### ISSUE TITLE
Ascalon Sword error DSVania and in game

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#40]
when using the Ascalon sword the game crashes, do you know what it can be?

NOTE: I never edited this sword

https://i.imgur.com/5T4wKX6.png

**Comment by LagoLunatic** [comment]
The Ascalon sprite's animation data is corrupted.

I recommend going back through your backups until you find the most recent backup in which it *wasn't* corrupted, and then figure out exactly what change you made after that point which corrupted the sprite. If you figure that out and tell me how to reproduce it I may be able to tell you how to avoid it in the future, or if it's a bug fix the bug.

**Comment by Urahara666** [comment]
I just discovered this error today and as I edit for years there is no backup in which the sword is working '-'

**Comment by Urahara666** [comment]
I think it happened when I tried to change some colors of the swords ... it looks like the palettes are shared or something

**Comment by LagoLunatic** [comment]
> I just discovered this error today and as I edit for years there is no backup in which the sword is working '-'

Unfortunate as it's probably nearly impossible to figure out what change caused the corruption without backups. In the future I recommend keeping a lot of backups.

> I think it happened when I tried to change some colors of the swords ... it looks like the palettes are shared or something

It's not possible for editing the colors in a palette with the GFX editor to corrupt an animation.

Let me know if you do get lucky and find a method of reproducing the issue.
