### ISSUE TITLE
DSVania crashes when clicking buttons in main window with no ROM loaded

### ISSUE THREAD

**Issue by Glaziaro** [LagoLunatic/DSVEdit#41]
I cannot extract any roms. I've tried Order of ecclesia and dawn of sorrow, and both just threw an error:
![extract](https://user-images.githubusercontent.com/49819705/112824999-86b82100-908b-11eb-8492-139d1ec1081b.PNG)

Also, when i try to click any button while there is no rom loaded, even the gray square, the program just crashes:
![crash](https://user-images.githubusercontent.com/49819705/112825093-a0f1ff00-908b-11eb-8d63-768ce902d22e.PNG)

Crashlog:
# Logfile created on 2021-03-29 12:34:47 +0200 by logger.rb/56815
E, [2021-03-29T12:34:47.533050 #6920] ERROR -- : undefined method `room_metadata_ram_pointer' for nil:NilClass (NoMethodError)
C:/Users/robin/Desktop/dsvania/dsvedit/main_window.rb:1304:in `copy_room_pointer_to_clipboard'
C:/Users/robin/Desktop/dsvania/lib/ruby/gems/2.4.0/gems/qtbindings-4.8.6.4-x64-mingw32/lib/Qt/qtruby4.rb:479:in `qt_metacall'
C:/Users/robin/Desktop/dsvania/lib/ruby/gems/2.4.0/gems/qtbindings-4.8.6.4-x64-mingw32/lib/Qt/qtruby4.rb:479:in `method_missing'
C:/Users/robin/Desktop/dsvania/lib/ruby/gems/2.4.0/gems/qtbindings-4.8.6.4-x64-mingw32/lib/Qt/qtruby4.rb:479:in `exec'
C:/Users/robin/Desktop/dsvania/./dsvedit.rb:28:in `<main>'

I am using Windows 10

**Comment by LagoLunatic** [comment]
> I cannot extract any roms. I've tried Order of ecclesia and dawn of sorrow, and both just threw an error:

The error is self explanatory. You're probably trying to load the european versions of the ROMs, which this program doesn't support as is mentioned in the readme.

> Also, when i try to click any button while there is no rom loaded, even the gray square, the program just crashes:

Thanks, I never thought to test that, I'll fix it.
