### ISSUE TITLE
Aria of Sorrow Swords and Enemies

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#42]
some enemies have disappeared from the scene and when I add back the swords are wrong and sometimes they even stop the game, can you solve it?
look at that.. merman disappeared and a sword got wrong
https://i.imgur.com/pvWxRiT.png
https://i.imgur.com/bS5z5wA.png
https://i.imgur.com/HqaXgbM.png
Bomb Armor disappeared too
other enemies from other areas as well

**Comment by LagoLunatic** [comment]
Not a helpful bug report. Explain the exact reproduction steps I would need to take to see the issue for myself.

**Comment by Urahara666** [comment]
some entities have also changed their position and the error happens when I try to move
I recorded the video and as soon as it is ready I put it here for you to take a look

**Comment by Urahara666** [comment]
https://drive.google.com/file/d/1e0-P7ztFwOBWrZf7vkXJOwkQmbw9Gz9K/view?usp=sharing

**Comment by piratesephiroth** [comment]
Don't record videos.
Write what did step by step.
It's even better if you can do that a clean ROM and confirm that you get the same bad results.

**Comment by Urahara666** [comment]
I don't know how to explain it with words, but the video already shows what I meant

**Comment by LagoLunatic** [comment]
If there are entities that far out of bounds and you didn't place them there, then your project is corrupted. Best to revert to a backup.

If you think the corruption was caused by DSVEdit, then like we said explain the reproduction steps for getting it to happen.

**Comment by Urahara666** [comment]
I changed some weapons and after a while without moving I went to play and there it was
entities out of bounds, enemies are gone and the game no longer saves after a while

**Comment by piratesephiroth** [comment]
That problem can only be solved if you can provide a way for it to be replicated.
Otherwise we can't even be sure if it was caused by DSVEdit or some other thing on your PC.

**Comment by Urahara666** [comment]
I think what corrupted my project was because I was messing with it while updating dsvania, I started the project with dsvania 1.7.0 and I changed a sword with it and when I changed to version 1.8.0 the sword no longer worked more and so on, what do you think?
