### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#45]
https://i.imgur.com/9mzo7O5.png

this error appeared to me '-'

**Comment by LagoLunatic** [comment]
Upload settings.yml

**Comment by Urahara666** [comment]
excuse me, don't I understand?

**Comment by LagoLunatic** [comment]
As the error says, it's crashing because it can't load your settings.yml file containing all your preferences. I'd like to look at this file. Otherwise I'll have no idea why the file got corrupted.

**Comment by LagoLunatic** [comment]
Well... your file was completely overwritten with null bytes. No idea how that's possible. I assume some sort of computer issue, fairly sure it can't be a bug in DSVEdit.

For now, delete the file and DSVEdit will be able to launch. I'll add code to automatically delete corrupted settings.txt files for future versions.
