### ISSUE TITLE
Having trouble figuring out ASM usage

### ISSUE THREAD

**Issue by TheBestNSMB** [LagoLunatic/DSVEdit#51]
Hey, how do I apply ASM patches from the DSVedit ASM folder to a rom? Also, are there any patches that may not work? (last time I tried my changes didn't show up in-game so that's why I'm asking.)

**Comment by piratesephiroth** [comment]
https://www.romhacking.net/forum/index.php?topic=23678.msg331577#msg331577

**Comment by LagoLunatic** [comment]
You just apply them normally, there's no secret
