### ISSUE TITLE
[enhancement] Add the posibbility of play with custom music.

### ISSUE THREAD

**Issue by pepodmc3** [LagoLunatic/DSVEdit#55]
Hello.
One option that would be completely killer would be the posibility of play the games with a custom ost.

I dont know if its feasible. For example, there is a guy that , created a external program that, along an emulator, played custom music when playing double dragon 2 for nes:

https://www.youtube.com/watch?v=KB0W79KjF2o

https://www.joflof.com/ddragon2.html

Can you make something like this but for the castlevania games? would be phenomenal to play with arranged tracks

**Comment by LagoLunatic** [comment]
Not planning to make this
