### ISSUE TITLE
rom file not present

### ISSUE THREAD

**Issue by Noobasik222** [LagoLunatic/DSVEdit#61]
why& i extract ROM give error: Failed to extract ROM with error:rom file not present.
C:/Program Files/DSVania/dsvlib/game.rb:44:in "Initialize_from_rom"
C:/Program Files/DSVania/dsvedit/main_windows.rb:338:in "block in extract rom"
C:/Program Files/DSVania/dsvedit/main_windows.rb:1408:in "block in execute"
And in console: Cancelled.
what to do?

**Comment by LagoLunatic** [comment]
It means you selected a file to open that doesn't actually exist on your hard drive.

I don't think that's possible to do by clicking on it, so I assume that you typed in a filename that doesn't exist manually or something?

**Comment by Noobasik222** [comment]
Thank you!
