### ISSUE TITLE
AoS: Problematic door

### ISSUE THREAD

**Issue by thegoldencoin** [LagoLunatic/DSVEdit#64]
I'm having an issue with a certain room transition in AoS. When I enter the room from the lefft, it loads just fine. However, when I enter from the right, there seems to be an issue with the player being put too far into the room, and the layers not being aligned properly. When I then walk far enough back to the right, even without exiting, the room corrects itself. 

Vid: https://www.youtube.com/watch?v=SwjOBMjlfuk

No other rooms have this issue. As far as I can tell, the door is configured correctly, and there's nothing special or unusual about the room itself, at least not as far as i can tell.

![image](https://user-images.githubusercontent.com/25706104/167487864-4fe219e5-0695-451e-ac11-48f314c0f9fd.png)

**Comment by LagoLunatic** [comment]
You probably set the room up wrong when creating it. This room didn't exist in vanilla. Make an IPS patch of your hack and upload the patch if you want me to be able to look into it.

**Comment by thegoldencoin** [comment]
Here ya go: https://drive.google.com/file/d/16w9RaTWw2C0CNM-SiZHYuZ9qMZVwE5JF/view?usp=sharing

For reference, this is the culprit room:
![image](https://user-images.githubusercontent.com/25706104/167494315-05f7a909-83ed-4eab-ab5d-110b1a438b02.png)

Thanks for your time! ^^

**Comment by LagoLunatic** [comment]
Change the Scroll Mode from 00 to 01 for layer 0 in that room.

Scroll Mode 00 seems to prevent the screen from scrolling properly. Not sure what purpose it serves, but I think the only rooms that used it in vanilla were rooms that don't scroll anyway (i.e. 1x1 rooms). Also no idea why it works from the left side.

**Comment by LagoLunatic** [comment]
Oh actually, mode 00 is probably intended for static background images like Julius's boss room. It's probably not coded to function correctly for the collision layer.

**Comment by thegoldencoin** [comment]
That seems to have solved it, indeed. Thanks ^^
