### ISSUE TITLE
DSV freeze 

### ISSUE THREAD

**Issue by Happylizard123** [LagoLunatic/DSVEdit#65]
when I change the text and save in the text editor, the app will freeze. Adding an item in the map will cause the app to freeze (app freezes before anything happen). I am running windows 10. 
I have no idea why this is happening to me and it does not seem like other people are having my issue.

**Comment by LagoLunatic** [comment]
Does it freeze temporarily and then start working after a minute?
Or does it stay frozen forever, no matter how long you wait?
Or does it crash? If it crashes, upload crashlog.txt.

**Comment by Happylizard123** [comment]
So I think I found out why. I was trying to edit a hacked rom.... when I start with a clean rom, everything works perfect. I am sorry and thank you.
