### ISSUE TITLE
Room View Zoom Level

### ISSUE THREAD

**Issue by Alice-Cheshire** [LagoLunatic/DSVEdit#68]
Would it be feasible to include the ability to zoom in when viewing rooms? On a 4k monitor, it's quite difficult to see things to the point where my mouse cursor is about twice the height of a zombie sprite when editing Aria of Sorrow and a bat sprite is around 1/8th the height of my cursor. Trying to move entities around can be finicky at this resolution as well.  A 200% and/or 400% zoom would be extremely helpful.

**Comment by LagoLunatic** [comment]
Implemented it if you wanna run from source. Zooming is done with ctrl+mousewheel and multiple zoom levels are available. It should be remembered across rooms (but not across sessions if you close and reopen DSVEdit). Barely tested so there might be bugs.

**Comment by Alice-Cheshire** [comment]
Thanks, I'll give running it from source a try later today when I have some more time.

> It should be remembered across rooms (but not across sessions if you close and reopen DSVEdit).

Personally I don't see that as a particular issue. Just having the ability to zoom in will help a ton.

**Comment by Alice-Cheshire** [comment]
https://i.imgur.com/kVwdFB1.png

So I'm trying to follow the run from source instructions but I'm getting this error at the `gem install bundler` step. What should I do from here?

**Comment by LagoLunatic** [comment]
Does `gem install bundler -v 2.1.4` work?

**Comment by Alice-Cheshire** [comment]
That appears to have done the trick. Everything else looks to have worked correctly after that too.

**Comment by LagoLunatic** [comment]
That's good to hear, I'll update the instructions

**Comment by piratesephiroth** [comment]
Could this zoom functionality be implemented in the sprite editor preview too?

**Comment by piratesephiroth** [comment]
Oh yeah it works great.
Could it be added to the skeleton editor as well?
