### ISSUE TITLE
DSVEdit - text editor

### ISSUE THREAD

**Issue by ThirdRookie** [LagoLunatic/DSVEdit#7]
Hello!
I found a little issue with text editor in DSVEdit tool. The program cannot accept foreign letters such as "á, ç, ë" etc. - these and others are exist in game font U version.
After applying one of these letters, text editor doesn't save them. In this case game does not show them in dialogue.

Could you please fix this little bug?

Thanks in advance and great job with tool!

**Comment by autofire372** [comment]
Reproduced in latest. "Valmanwë" in DSVEdit shows up as "Valmanw" as soon as the name change is confirmed via OK. This is what displays in-game as well.
