### ISSUE TITLE
Item drop formula for Portrait of Ruin?

### ISSUE THREAD

**Issue by SilentHeII** [LagoLunatic/DSVEdit#75]
I noticed that Portrait of Ruin didn't have documentation on the item drop formula.

Would a similar formula to the wiki be the key? I noticed this formula generates values within 0.01% of error from those displayed by the Gambler's Glasses.

(Base Chance)×(52+LCK)/(52×256)

e.g. 
![image](https://user-images.githubusercontent.com/29898818/226825218-768c105e-671a-46b7-96e0-918333b63e77.png)
Frilly Camisole has a base chance of 8 while Pudding Bucket has base chance of 4.

When I follow the formula above I get 8.59% and 4.29% respectively. I'm trying to work out if either the error is due to rounding or if there is any other change that can be made to the formula.

**Comment by LagoLunatic** [comment]
I just looked through the code, and it seems the formula is this:
drop% = (base_chance * (100 + (LCK * 1.92))) / divisor
Where:
* LCK is the controlled player's LCK value
* base_chance is the number from the enemy DNA, plus the number of Thief Rings the controlled player has equipped
* divisor is 256, minus 4 times the number of Thief Rings the controlled player has equipped
