### ISSUE TITLE
info on AoS Debug Mode 

### ISSUE THREAD

**Issue by TsukiZero** [LagoLunatic/DSVEdit#78]
While exploring Debug → 1967 → SDTEST I made the following findings:

Despite SDTEST providing no visual feedback, use Memory viewer to observe:
- Up and Down switches Sound Mode.
- Left and Right decrements and increments by 0x01 in the specific addresses based on the sound mode (see below).
- A and B selects which audio byte is to be loaded. A plays and B stops.
- Sound mode is located at 020254D6 and has an 8-bit value (0x00):
   - 00 = Music and affects the 16-bit value at 020254D8, ranges from 0x0000 to 0x0024
   - 01 = Sound and affects the 16-bit value at 020254DA, ranges from 0x0064 to 0x0170
   - 02 = Voice and affects the 16-bit value at 020254DC, ranges from 0x0190 to 0x01EE

I don't know if it may be of use, but perhaps through that you could find out where the sounds are stored and create a sound player for DSVania Editor to help users pick sounds for their monsters, souls and weapons, maybe even find a way to export and import sounds.

**Comment by LagoLunatic** [comment]
I don't know anything about GBA sound import and export and don't intend to look into it. But I assume that GBA sound hacking tools probably exist out there somewhere.
