### ISSUE TITLE
por_fix_map_explore_bug not applying

### ISSUE THREAD

**Issue by Silver-D** [LagoLunatic/DSVEdit#8]
Hi! I am having an issue with the patch in the title. I am using the 1.7.2 release, and I am getting this error: 
![screen shot 2018-10-31 at 18 01 51](https://user-images.githubusercontent.com/6107417/47797348-3bbd4680-dd37-11e8-8a90-833a0188c333.png)

I have also tried copying the updated version from the repo and I get the same error.
Other patches like nerfing enemy resistances and skip emblem drawing apply fine.

**Comment by LagoLunatic** [comment]
That's strange, I've never seen that error before. Not sure what it could mean.

To be clear, there's three requirements before you can apply that patch and have it work correctly (or any patch that uses free space):
* You need to be using the matching version of DSVEdit (1.7.2 for the first version of this patch, or for the fixed version of the patch, you need to use the source version of DSVEdit)
* You must add a new free space overlay to your PoR project
* You must make sure you haven't used the place in memory for that patch for anything else, or else the patch will overwrite the other thing that was there without telling you, and it will cause serious issues. If you've already used that place in memory for something else, you can edit the patch to use a different place in memory before applying it.

But even if you don't meet those requirements it shouldn't give you that specific error, so I dunno.

**Comment by LagoLunatic** [comment]
Actually, I have an idea as to what might cause that error. DSVEdit doesn't know whether it should run the 32 bit or 64 bit version of armips, so it tries running the 32 bit version first, and if it runs into an error it runs the 64 bit version instead.

If you're on a 32 bit computer, but there's some unrelated error when running the 32 bit armips (e.g. you didn't add a free space overlay), it wouldn't show that error and instead would try to run 64 bit armips, which could cause weird errors like that on a 32 bit computer.

**Comment by Silver-D** [comment]
I am so sorry this is all my fault. I of course read the instructions, but somehow thought that adding freespace layer was only needed if I wanted to apply my own asm code, not yours. Of course it makes now. It applied and works!

However, you are right. I am running your wonderful tool ina  32-bit Wine bottle, so your deduction with the asm patcher error was probably spot on.

Sorry for this!

**Comment by LagoLunatic** [comment]
DSVEdit should at least display the correct error message though - if it had said "Could not open file overlay9_119" you might have been able to figure it out. I made a change to try to detect 32 bit computers and not try to run 64 bit armips in that case, so hopefully that error won't happen again.
