### ISSUE TITLE
Aria of Sorrow: New rooms don't have music?

### ISSUE THREAD

**Issue by fcard** [LagoLunatic/DSVEdit#84]
I've looked everywhere and I don't see a way to set a song for a room, it seems like they are preset based on area, but newly created rooms don't inherit this property. I might be missing something.

**Comment by LagoLunatic** [comment]
The room needs to be located on a map tile. The map data is what tells the game what sector (and therefore what music) is for the location on the map the player is in. DSVEdit automatically updates the map tile's sector index to match the room itself so they aren't different from each other. But if you haven't placed the new room on the map editor, then its tile can't have any sector index set.
