### ISSUE TITLE
Invalid shift jis character

### ISSUE THREAD

**Issue by p-estor** [LagoLunatic/DSVEdit#87]
Hi,

Not really an issue, but I don't know where to get any help with this.

I am struggling to translate text because the only way I have found that works so far is copy & pasting from a shift-jis char, is there any way to just typing shift-jis in the editor?

Thanks

**Comment by LagoLunatic** [comment]
I'm not sure if I understood you, but basically it sounds like you're trying to type new JP text and sometimes it works but occasionally you get an error saying the character is unknown?

That would be because you typed a kanji that isn't present in the game's font. The game can only display characters that exist in its font.

**Comment by p-estor** [comment]
I am sorry. I mean I want to type romanized characters because I want to translate  some texts to English.

I managed to get some romanized characters work copy & pasting from [here](http://www.rikai.com/library/kanjitables/kanji_codes.sjis.shtml), but it would be great I could just type shift-jis instead of copy & pastings.

**Comment by LagoLunatic** [comment]
That should already work. I just tried it, switching my Japanese IME mode to "Full-width alphanumeric" and then typing Soma on my keyboard, and it resulted in the shift JIS text Ｓｏｍａ, which I saved with no issue:
![image](https://github.com/user-attachments/assets/ea260dd8-bfcc-431d-90e2-f424aaf194c6)

You should double check that you have the correct IME mode set. "Half-width alphanumeric" isn't correct.

**Comment by p-estor** [comment]
I am so stupid, I tried some "width" before using Google IME but since they didn't work I didn't try the rest. 

It worked using full-width, thanks a lot. :)
