### ISSUE TITLE
Rom hacking advice reques. PoR Co-Op

### ISSUE THREAD

**Issue by Just-Luis** [LagoLunatic/DSVEdit#88]
Hi! I've been trying to make a hack that makes it possible to play the hole game in wireless co-op. I have already decompiled the game and have been playing around with pointers and addresses, but to be honest, I feel a little lost. It seems you have documented very thoroughly the single-player aspect of this game, but there is very little information in regards to co-op, so if there is any advice, information, or help you could provide, I'd be more than thankful.

I know this is not the place to ask for help but I couldn't find a way to get in touch privately

**Comment by LagoLunatic** [comment]
I don't know anything about the game's co-op/wifi mode. I don't even know how you'd emulate it. You'll have to ask someone else.

**Comment by Just-Luis** [comment]
Understandable. MelonDS allows for wireless connection, and RAM inspection, though it doesn't have memory view or a disassembler. I'd see if someone knows about it. Thankyou very much for replaying so quickly though
